version: "3"

name: "infrastructureunias"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5440:5432"
    volumes:
      - "C:/Users/DELL/apps/appunias:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=cmlsolutions
      - POSTGRES_DB=app-scheduling-project
    restart: unless-stopped